# Spring JPA
spring:
  datasource:
    url: jdbc:postgresql://articledatabase:5432/article_dev
    username: postgres
    password: postgres
  zipkin:
    baseUrl: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8099/realms/kt-realm
          jwk-set-uri: http://keycloak:8099/realms/kt-realm/protocol/openid-connect/certs

  cloud:
    stream:
      bindings:
        input:
          destination: articleLikeTopic
          content-type: application/json
          group: article-like-service
      kafka:
        binder:
          zkNodes: kafka
          brokers: kafka

# Eureka
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
