# Spring JPA ??
spring:
  datasource:
    url: jdbc:postgresql://database:5432/article_dev
    username: postgres
    password: postgres

# Eureka ??
eureka:
  instance:
    preferIpAddress: true
    registerWithEureka: true
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
