# Spring JPA
spring:
  datasource:
    url: jdbc:postgresql://commentdatabase:5432/comment_dev
    username: postgres
    password: postgres
  zipkin:
    baseUrl: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8099/realms/kt-realm
          jwk-set-uri: http://keycloak:8099/realms/kt-realm/protocol/openid-connect/certs
# Eureka
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/