# Spring JPA
spring:
  datasource:
    url: jdbc:postgresql://commentdatabase:5432/comment_dev
    username: postgres
    password: postgres

# Eureka
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/